#!/bin/sh

icon=""
class=$(playerctl metadata --player=spotify --format '{{lc(status)}}' 2>&1)
info=$(playerctl metadata --player=spotify --format '{{artist}} - {{title}}' 2>&1)

if [[ ${#info} > 60 ]]; then
	info=$(echo $info | cut -c1-60)"..."
fi

if [[ $class == "playing" ]]; then
	text=$icon" "$info" "
elif [[ $class == "paused" ]]; then
	text=$icon" "$info" "
elif [[ $class == "stopped" ]]; then
	text=$icon" "
elif [[ $class == "No players found" ]]; then
	text=""
else
	text=$icon" Error "
fi

echo -e "{\"text\":\""$text"\", \"class\":\""$class"\"}"

