###############################################################################
# Services settings                                                           #
###############################################################################
# Web services definitions.
# SMASH, SMELT, IBS and OBS are required. PackageServer is optional, but
# required if used in the `search` command. Mitre is required for the `khelper`
# command

# SMASH
[[settings.services]]
# service name, mandatory. Will be used for internal service
# lookup (case-insensitive).
name = 'SMASH'

# API URL, mandatory. If a scheme (e.g. https://) is not specified, 'https://'
# will be automatically prepended
api = 'smash.suse.de'

# host URL. If a scheme (e.g. https://) is not specified, 'https://' will be
# automatically prepended
host = 'smash.suse.de'

# SMELT
[[settings.services]]
# service name, mandatory. Will be used for internal service
# lookup (case-insensitive).
name = 'SMELT'

# API URL, mandatory. If a scheme (e.g. https://) is not specified, 'https://'
# will be automatically prepended
api = 'smelt.suse.de'

# Package Server
[[settings.services]]
# service name, mandatory. Will be used for internal service
# lookup (case-insensitive).
name = 'PackageServer'

# API URL, mandatory. If a scheme (e.g. https://) is not specified, 'https://'
# will be automatically prepended
api = 'http://sec-gsonnu.suse.de:5000'

[[settings.services]]
# service name, mandatory. Will be used for internal service
# lookup (case-insensitive).
name = 'Mitre'

# API URL, mandatory. If a scheme (e.g. https://) is not specified, 'https://'
# will be automatically prepended
api = 'cveawg.mitre.org'

# OBS
[[settings.services]]
# service name, mandatory. Will be used for internal service
# lookup (case-insensitive).
name = 'OBS'

# API URL, mandatory. If a scheme (e.g. https://) is not specified, 'https://'
# will be automatically prepended
api = 'api.opensuse.org'

# only include these projects in results. Glob patterns (*) can be used.
# Defaults to empty list.
projects.include = [
    'openSUSE:Factory',
    'openSUSE:Backports:SLE-15-SP4',
    'openSUSE:Backports:SLE-15-SP5'
]

# exclude these projects from results. Matching rules are the same as the
# 'project.include' section. Defaults to empty list.
projects.exclude = [
    '*:Rings:*',
    '*:Staging:*',
    '*:RISCV',
    '*:SLECandidates',
    '*:ToTest',
    '*:ARM',
    '*:zSystems',
    '*:PowerPC'
]

# IBS
[[settings.services]]
# service name, mandatory. Will be used for internal service
# lookup (case-insensitive).
name = 'IBS'

# API URL, mandatory. If a scheme (e.g. https://) is not specified, 'https://'
# will be automatically prepended
api = 'api.suse.de'

# only include these projects in results. Glob patterns (*) can be used.
# Defaults to empty list.
projects.include = [
    'SUSE:*',
    'NON_Public:*'
]

# exclude these projects from results. Matching rules are the same as the
# 'project.include' section. Defaults to empty list.
projects.exclude = [
    'SUSE:Factory:Head',
    'SUSE:Carwos:1:*',
    'SUSE:Carwos:2:*',
    'SUSE:Maintenance:*',
    'SUSE:Updates:*',
    '*:Staging:*',
    '*:Rings:*',
    '*:MOVED_OLDPROJECT',
    '*:Test',
    '*:BCI',
    '*:CR',
    '*:ToTest'
]


###############################################################################
# Repositories settings                                                       #
###############################################################################
# Repository definition, available to use for commands. Both 'git' and
# 'obs'/'ibs' type repository are supported.
# Repositories management could be done either by the application (if
# 'general.maintenance.enable' is set to true) or by the user.
# If repositories are managed by the application:
#   * if a repository doesn't already exist it will be checked out. If branches
#     are specified those branches will be also checked out.
#   * If a repository already exists, it will be updated and specified branches
#     will be checked out or pruned if the one in the repository differs from
#     the ones in the configuration file.
#
# If the 'branches' field is not specified only the main repository branch is
# used.
# Note that the application doesn't change the content of any repository, but
# only changes the local copy. So is not advisable to manually change contents
# for managed repositories.
#
# 'kernel-source' and 'kernel-patches' repositories are mandatory.

# SUSE unpacked kernel repository
[[settings.repositories]]
# repository name, mandatory. Will be used for internal repository
# lookup (case-insensitive).
name = 'kernel-sources'

# repository type, mandatory. One of 'git', 'ibs', 'obs' (case-insensitive).
type = 'git'

# repository unique identifier, mandatory. Used in 'checkout' operation.
id = 'git://kerncvs.suse.de/kernel.git'

# SUSE packed kernel repository
[[settings.repositories]]
# repository name, mandatory. Will be used for internal repository
# lookup (case-insensitive).
name = 'kernel-patches'

# repository type, mandatory. One of 'git', 'ibs', 'obs' (case-insensitive).
type = 'git'

# repository unique identifier, mandatory. Used in 'checkout' operation.
id = 'git://kerncvs.suse.de/kernel-source.git'

###############################################################################
# Kernel specific settings                                                     #
###############################################################################
# branches to track
[settings.kernel]
branches = [
    # regular branches
    'SLE12-SP5',
    'SLE15-SP5',
    'SLE15-SP6',
    'ALP-current',
    'stable',
    # LTSS branches
    'SLE11-SP4-LTSS',
    'SLE12-SP3-LTSS',
    'SLE12-SP3-TD',
    'SLE15-SP2-LTSS',
    'SLE15-SP3-LTSS',
    'SLE15-SP4-LTSS',
    # reactive supported branches
    'SLE15-LTSS',
    'SLE12-SP2-LTSS',
    'SLE12-SP4-LTSS',
    'SLE15-SP1-LTSS',
    # CVE branches
    'cve/linux-4.4-LTSS',
    'cve/linux-5.3-LTSS',
    'cve/linux-5.14-LTSS'
]

###############################################################################
# SMASH specific settings                                                     #
###############################################################################
[settings.smash]
build_service = 'IBS'

blacklist = [
    'kernel-azure',
    'kernel-debug',
    'kernel-default',
    'kernel-default-base',
    'kernel-docs',
    'kernel-ec2',
    'kernel-obs-build',
    'kernel-preempt',
    'kernel-rt',
    'kernel-rt_debug',
    'kernel-syms',
    'kernel-syms-azure',
    'kernel-syms-rt',
    'dtb-aarch64',
    'kernel-zfcpdump',
    'kernel-64kb',
    'kernel-obs-qa',
    'kernel-kvmsmall'
]

[settings.smash.dependencies]
'kernel-source-azure' = 'kernel-source'
'kernel-source-rt' = 'kernel-source'
'SUSE:Carwos:1/kernel-source-rt' = 'SUSE:SLE-15-SP2:Update/kernel-source'
'*:Products:SLERT:Update/kernel-source-rt' = '*/kernel-source'
'SUSE:SLE-12:Update/ruby' = 'SUSE:SLE-12:Update/ruby2.1'
'SUSE:SLE-15:Update/ruby' = 'SUSE:SLE-15:Update/ruby2.5'

[settings.smash.kernel_map]
'SUSE:ALP:Source:Standard:1.0' = ['ALP-current', 'SLE15-SP6']
'SUSE:SLE-11-SP4:Update' = ['SLE11-SP4-LTSS']
'SUSE:SLE-12-SP2:Update' = ['SLE12-SP2-LTSS', 'cve/linux-4.4-LTSS']
'SUSE:SLE-12-SP3:Update' = ['SLE12-SP3-LTSS', 'cve/linux-4.4-LTSS']
'SUSE:SLE-12-SP3:Update:Products:Teradata:Update' = ['SLE12-SP3-TD', 'cve/linux-4.4-LTSS']
'SUSE:SLE-12-SP4:Update' = ['SLE12-SP4-LTSS']
'SUSE:SLE-12-SP5:Update' = ['SLE12-SP5']
'SUSE:SLE-15:Update' = ['SLE15-LTSS']
'SUSE:SLE-15-SP1:Update' = ['SLE15-SP1-LTSS']
'SUSE:SLE-15-SP2:Update' = ['SLE15-SP2-LTSS', 'cve/linux-5.3-LTSS']
'SUSE:SLE-15-SP3:Update' = ['SLE15-SP3-LTSS', 'cve/linux-5.3-LTSS']
'SUSE:Carwos:1' = ['SLE15-SP2-LTSS', 'cve/linux-5.3-LTSS']
'SUSE:SLE-15-SP4:Update' = ['SLE15-SP4-LTSS', 'cve/linux-5.14-LTSS']
'SUSE:SLE-15-SP5:Update' = ['SLE15-SP5', 'cve/linux-5.14-LTSS']
'SUSE:SLE-15-SP6:Update' = ['SLE15-SP6']
'SUSE:SLE-12-SP5:Update:Products:SLERT:Update' = ['SLE12-SP5']
'SUSE:SLE-15-SP3:Update:Products:SLERT:Update' = ['SLE15-SP3-LTSS', 'cve/linux-5.3-LTSS']
'SUSE:SLE-15-SP4:Update:Products:SLERT:Update' = ['SLE15-SP4-LTSS', 'cve/linux-5.14-LTSS']

