###############################################################################
# General settings                                                            #
###############################################################################
[general]

# enable or disable logs. Defaults to false
log.enable = true

# log level. One of: 'info', 'debug', 'warning', 'error', 'critical'.
# Defaults to 'info'
log.level = 'debug'

# log directory. A path. Path expansion ('~' and '~user') and variables
# expansion (in the form `$var` and `${var}`) are supported. If the directory
# doesn't exist will be created. Log files will be named 'imtools-<pid>.log'.
# Defaults to '/tmp/imtools_logs/'
log.directory = '~/.local/share/imtools-dev/logs'

# use keyring for looking up credentials for services. If true, the username
# field must be set, and the other fields value will be used for service
# lookup. Defaults to false.
keyring = true

# max simultaneous workers to use. If not specified, a value based on the
# number of CPUs in the system will be used.
workers = 25

# enable paginated output with less. Defaults to true
paging = false

# enable colored output. Defaults to true.
colors = true

# data directory. A path. Path expansion ('~' and '~user') and variables
# expansion (in the form `$var` and `${var}`) are supported. If the directory
# doesn't exist will be created.
# Defaults to '${XDG_DATA_HOME}/imtools'
# data.directory =

# cache directory. A path. Path expansion ('~' and '~user') and variables
# expansion (in the form `$var` and `${var}`) are supported. If the directory
# doesn't exist will be created.
# Defaults to '${XDG_CACHE_HOME}/imtools'
cache.directory = '~/.cache/SUSE'

# cache freshness. Number of seconds for which a cache element is considered
# "fresh".
# Can be a number or a string in the form '<number><unit>'. Available units:
# - s: seconds
# - m: minutes
# - h: hours
# - d: days
# - w: weeks
# If unit is omitted the number is interpreted as seconds. Defaults to '1d'.
cache.freshness = '1d'

# automatically run maintenance (update repositories, prune caches, etc.) when
# needed. Defaults to false.
maintenance.enable = true

# maintenance update interval. Number of seconds before maintenance is run.
# Can be a number or a string in the form '<number><unit>'. Available units:
# - s: seconds
# - m: minutes
# - h: hours
# - d: days
# - w: weeks
# If unit is omitted the number is interpreted as seconds. Defaults to '1d'.
maintenance.interval = '1d'

# osc command. Must refer to a command on $PATH. Shell aliases are not
# supported. Defaults to 'osc'
tools.osc = 'osc'

###############################################################################
# Credentials settings                                                           #
###############################################################################
# Credentials definition.

# SMASH
[credentials.smash]
# username. Mandatory if general.keyring is true, as it will be used for
# SecretService lookup
username = 'crazybyte'

# API token. If general.keyring is true, this value will be used for
# SecretService lookup
token = 'smash-token'

# IBS
[credentials.ibs]
# username. Mandatory if general.keyring is true, as it will be used for
# SecretService lookup
username = 'crazybyte'

# SSH Key file
key = '~/.ssh/crazybyte_at_SUSE-EandI.pub'

# OBS
[credentials.obs]
# username. Mandatory if general.keyring is true, as it will be used for
# SecretService lookup
username = 'crazybyte'

# API token. If general.keyring is true, this value will be used for
# SecretService lookup
password = 'api.opensuse.org'

# SUSE Bugzilla
[credentials.bugzilla]
# username. Mandatory if general.keyring is true, as it will be used for
# SecretService lookup
username = 'crazybyte'

# API token. If general.keyring is true, this value will be used for
# SecretService lookup
token = 'bugzilla-token'

###############################################################################
# Repositories settings                                                       #
###############################################################################
[repositories]
# kernel repositories to use. Available values: 'kernel-sources', 'kernel-branches', 'kernel-history'.
# Default: 'kernel-sources', 'kernel-patches'
# kernel = ['kernel-sources', 'kernel-patches']
kernel = ['kernel-sources']

[repositories.path]

# SUSE unpacked kernel repository
kernel-sources = '~/.local/share/SUSE/kernel'

# SUSE packed kernel repository
# kernel-patches = '~/.local/share/SUSE/kernel-source'

###############################################################################
# Commands settings                                                           #
###############################################################################

# 'extract' command settings
[commands.extract]

# tar command. Must refer to a command on $PATH. Shell aliases are not
# supported. Defaults to 'tar'.
tar = 'tar'

# unzip command. Must refer to a command on $PATH. Shell aliases are not
# supported. Defaults to 'unzip'.
unzip = 'unzip'

# cpio command. Must refer to a command on $PATH. Shell aliases are not
# supported. Defaults to 'cpio'.
cpio = 'cpio'

# quilt command. Must refer to a command on $PATH. Shell aliases are not
# supported. Defaults to 'quilt'.
quilt = 'quilt'

# phar command. Must refer to a command on $PATH. Shell aliases are not
# supported. Defaults to 'phar'.
phar = 'phar'

# 'grep' command settings
[commands.grep]
# groups all similar matches into one. If false print every match.
# Defaults to true.
group.enable = true

# display match information in a list instead of a table in group mode.
# Defaults to true.
group.list = true

# show full path in group mode. If false, only show relative path to source
# directory, Defaults to false.
group.full_path = false

# ignore trailing whitespace when comparing two matches in group mode.
# Defaults to true.
group.whitespace.ignore = true

# 'search' command settings
[commands.search]
# Enable strict matching or not. Can be overridden with command-line switches.
# Defaults to false.
strict = false

# Do not apply any filter to search results. Setting it to true will show
# all results from 'ibs' or 'obs' providers, without filtering the projects
# specified in the 'projects.include' and 'projects.exclude' sections of the
# IBS or OBS service definition. Can be overridden with command-line switches.
# Defaults to false.
full = false

# columns to show. Can be overridden with command-line switches.
# Defaults to ['software', 'matches'].
columns = ['software', 'matches']

# providers to enable. Can be overridden with command-line switches.
# Defaults to ['ibs', 'obs'].
#providers = ['ibs', 'obs', 'packageserver']
providers = ['packageserver']

# use a column separator when printing results. Defaults to true.
separator.column = false

# use a row separator when printing results. Defaults to true.
separator.row = false

# highlight match in results. Defaults to true.
match.highlight = true

# 'clean' command settings
[commands.clean]
# verbose mode
verbose = false

# resolve policy
policy = 'strict'

# category to use as default in `auto` mode (-a flag)
auto.category = 'security'

# issue state to use in `auto` mode (-a flag)
auto.state = 'revisit'

# filter to use in `auto` mode (-a flag)
auto.filter = 'bnc#'

# 'container' command settings
[commands.container]
# container manager. Must refer to a command on $PATH. Shell aliases are not
# supported. Defaults to 'podman'.
manager = 'podman'

# container image repository. will be added to container
# name: {repository}/{container_name}. Can be overridden per container
# in container definition.
repository = 'security'

# container home directory. Defaults to '/root'. Can be overridden per
# container in container definition
home = '/root'

# container shell. Defaults to '/bin/bash'. Can be overridden per
## container in container definition
shell = '/bin/bash'

# containers to use.
# A container definition contain the following fields:
#  * image: container image [MANDATORY]
#  * alias: custom container alias, must be unique [OPTIONAL]
#  * scc: use SCC credentials defined in main 'scc' field [OPTIONAL]
#  * repository: use this repository instead of the one in the main
#                'repository' field [OPTIONAL]
#  * home: use this home directory instead of the one in the main 'home'
#          field [OPTIONAL]
#  * shell: use this shell instead of the one in the main 'shell'
#    field [OPTIONAL]
#  * volumes: mount this volumes in addition to the ones specified in the
#             main 'volumes' field [OPTIONAL]
#list = [
#    # openSUSE Leap 15.4
#    { image = 'leap:15.4', alias = 'leap154' },
#    # openSUSE Leap 15.5
#    { image = 'leap:15.5', alias = 'leap155' },
#    # openSUSE Leap 15.6
#    { image = 'leap:15.6', alias = 'leap156' },
#    # openSUSE Tumbleweed
#    { image = 'tumbleweed', alias = 'tw' },
#    # SLE 12 SP3
#    { image = 'sle:12.3', alias = 'sle123', scc = true },
#    # SLE 12 SP4
#    { image = 'sle:12.4', alias = 'sle124', scc = true },
#    # SLE 12 SP5
#    { image = 'sle:12.5', alias = 'sle125', scc = true },
#    # SLE 15
#    { image = 'sle:15.0', alias = 'sle150', scc = true },
#    # SLE 15 SP1
#    { image = 'sle:15.1', alias = 'sle151', scc = true },
#    # SLE 15 SP1
#    { image = 'sle:15.2', alias = 'sle152', scc = true },
#    # SLE 15 SP2
#    { image = 'sle:15.3', alias = 'sle153', scc = true },
#    # SLE 15 SP3
#    { image = 'sle:15.4', alias = 'sle154', scc = true },
#    # SLE 15 SP4
#    { image = 'sle:15.5', alias = 'sle155', scc = true },
#    # SLE 15 SP6
#    { image = 'sle:15.6', alias = 'sle156', scc = true }
#]

list = []

# container common volumes
# volumes to mount in every container. In the form <source> = <destination>.
# <source> should refer to an existing path on the system, otherwise it will be
# ignored. Path expansion ('~' and '~user') and variables expansion (in the
# form `$var` and `${var}`) are supported.
# [commands.container.volumes]
# '<src>' = '<dst>'

#  SCC credentials to use. Same format as 'commands.container.volumes' field
[commands.container.scc]
'~/.config/SUSE/secrets/SCCcredentials' = '/etc/zypp/credentials.d/SCCcredentials'
'~/.config/SUSE/secrets/SUSEConnect' = '/etc/SUSEConnect'

# 'khelper' command settings
[commands.khelper]

# compresses the log generated by `git log` to take less space. Defaults to true
log.compress = true

